#!/bin/bash
Dir="$HOME/.config/dwm/dwmbar/scripts"
while [[ true ]]; do 
  Clock2="$($Dir/clock2)"
  Mem="$($Dir/memory)"
  Vol="$($Dir/volume)"
  Bat="$($Dir/battery)"
  xsetroot -name " $Mem $Vol $Bat $Clock2"
  sleep 1
done
