#! /bin/bash

eleccion=$(printf "Poweroff \nReboot \nSuspend 󰤄\nLogout " | dmenu -i )

case "$eleccion" in
	"Poweroff ") loginctl poweroff ;;
	"Reboot ") loginctl reboot ;;
	"Suspend 󰤄") loginctl suspend ;;
	"Logout ") loginctl kill -9 -1 ;;
	*) exit 1 ;;
esac
