#! /bin/bash

eleccion=$(printf "Poweroff \nReboot \nSuspend 󰤄\nLock " | dmenu -i )

case "$eleccion" in
	"Poweroff ") systemctl poweroff ;;
	"Reboot ") systemctl reboot ;;
	"Suspend 󰤄") systemctl suspend ;;
	"Lock ") kill -9 -1 ;;
	*) exit 1 ;;
esac
