#!/bin/bash

Wallpaper_main="$HOME/.cache/wal/wal"
Wallpaper_rescue="$HOME/Wallpapers/city.png"


if [[ -f "$Wallpaper_main" ]]; then
    wal_image=$(cat "$Wallpaper_main")
    feh --bg-fill "$wal_image"
else
    feh --bg-fill "$Wallpaper_rescue" 
fi
