#! /bin/bash

# Ruta donde están los wallpapers
Wallpapers_dir="$HOME/Wallpapers"

# Obtener solo los nombres de los archivos en lugar de las rutas completas
Wallpaper=$(find "$Wallpapers_dir" -type f -printf "%f\n" | dmenu -i -l 18 )

# Verificar si se seleccionó una imagen
if [ -n "$Wallpaper" ]; then
    # Cambiar el fondo de pantalla usando la ruta completa
    feh --bg-scale "$Wallpapers_dir/$Wallpaper" && notify-send -u low "  Wallpaper" "$Wallpaper"
fi
